export const CATEGORIES = {
  ENTERTAINMENT: 'ENTERTAINMENT',
  SOCIAL: 'SOCIAL',
  SHOPPING: 'SHOPPING',
  PRODUCTIVE: 'PRODUCTIVE',
  UNKNOWN: 'UNKNOWN'
};

export const DOMAIN_MAPPING = {
  'youtube.com': CATEGORIES.ENTERTAINMENT,
  'netflix.com': CATEGORIES.ENTERTAINMENT,
  'instagram.com': CATEGORIES.SOCIAL,
  'twitter.com': CATEGORIES.SOCIAL,
  'x.com': CATEGORIES.SOCIAL,
  'facebook.com': CATEGORIES.SOCIAL,
  'coupang.com': CATEGORIES.SHOPPING,
  'amazon.com': CATEGORIES.SHOPPING,
  'github.com': CATEGORIES.PRODUCTIVE,
  'notion.so': CATEGORIES.PRODUCTIVE,
  'docs.google.com': CATEGORIES.PRODUCTIVE
};

export const EVOLUTION_THRESHOLDS = {
  ENTERTAINMENT: 10 * 60, // 10 minutes in seconds
  SOCIAL: 10 * 60,
  SHOPPING: 5 * 60,
  PRODUCTIVE: 30 * 60
};

export const PET_STATES = {
  NORMAL: 'NORMAL',
  FAT: 'FAT',
  ARROGANT: 'ARROGANT',
  BEGGAR: 'BEGGAR',
  WORKING: 'WORKING'
};
